dist: xenial
language: python
python:
- 3.6.9
- '3.7'
install:
- pip install -r requirements.txt
script:
- "/bin/bash -c ci/run.sh"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: C+hKXQtTDmgioSjK8HRYgRkUI4f5kdALXv0Dp2kdjor84HMx1qPp5/IAy1j0WHb/s5fxG07t/Qp+qFV4QNnYB7yELya9+gA6S5DDzKsbg++wtndK4Q9dAnyHtytr+qM8uS/y2gi2AUmkH9kQfBfyyV8FRusBEi6hsuSx4bd3mWh1WuN79Ip20ShNmm/9jz42Y5oJk4rB0mIJ8k/d/jQX3q7HdfSuOv8nlJDAmod+WTHIzilQfCOU5xkRieQkJ5HAgW7o/TntNh7Zb6dzmR5VW5xIZAvfXuZkyFaZuCArkpL5pUjjQS4yJFto2LriK2+J9n9v3+BeTRYNVPJimB8eA9SKQrC8Z7oGjob0XOgHgPzD62J02PBWK2Jh8XW2H71up3pcRhcLSwKB13N7kbaSRyJfwEHDSnO9rMLK8PhrrQHiHUs/BW4hv+lxjWjLqZ01ae2b2njwC98Jla5ihWrsYcKDW+bd5xWm9TDg9BF6aGXluy3JdDMGNcMDW1H+9cJ2XHjilDsV8nghvGHgYQXRounCB8B9h25Gy3yD1j3EiEO4bvl4BhhpKzpzoPvT5y7VH/bGBtOZepOGWc2++WlZig214ll5W294L/swqoskVklxFhgDdy6Q9BBt75pqQRPRuoORwZkuPGWCOf3UO444vZus+Diu/3+WafhdNhetEaA=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
